---
title: "brazil_covid_national"
output: html_notebook
---
Erin Abbott 


Find covid case weighted centroids at the national level based on weekly case counts at the municipality level. 

DATA PREP
```{r}
library(dplyr)
library(sf)
library(tmap)
library(tidyverse)
library(tmap)
library(stplanr)


state <- st_read("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_state_shapefile/Brazil_state_shapefile.shp" )
state <- state %>% rename(state_code = CD_GEOCUF) %>% st_transform(., 29101)
state$state_code <- as.character(state$state_code)
state["country_code"] <- "BRA"
state_simple <- rmapshaper::ms_simplify(state, keep = 0.1,keep_shapes = TRUE)
setwd("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_data_for_geographical_center/")
#st_write(state_simple, "state_simple", driver="ESRI Shapefile")


munic <- st_read("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_municipalities_shapefile/Brazil_municipalities_shapefile.shp")
munic <- munic %>% rename(ibge_code = CD_GEOCMU) %>% st_transform(., 29101)
munic$ibge_code <- as.character(munic$ibge_code)
munic <- munic %>% st_as_sf(.) %>% st_make_valid(.)
munic["country_code"] <- "BRA"
munic <- munic %>% mutate(state_code = substring(ibge_code,1,2)) %>% select(NM_MUNICIP, ibge_code, state_code, country_code)

cases <- read.csv("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_data_for_geographical_center/all_epi_week_daily_deaths_cases_by_mun_and_state.csv")
cases$ibge_code <- as.character(cases$ibge_code)
allcases2 <- cases


brazil <- state_simple %>% group_by(country_code) %>% summarise(num_states= n())
head(brazil)

setwd("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_data_for_geographical_center/")
#st_write(brazil,"brazil.shp", driver = "ESRI Shapefile")

brazil_geogcent <- st_centroid(st_geometry(brazil))
state_geogcent <- st_centroid(st_geometry(state))
state_simple_geogcent <- st_centroid(st_geometry(state_simple))
munic_geogcent <- st_centroid(st_geometry(munic))

capital <- st_read("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/Brazil_state_capitals/Brazil_state_capitals.shp")
capital <- capital %>% filter(FEATURECLA=="Admin-0 capital") %>% st_transform(29101)



tm_shape(brazil) + tm_borders() + tm_shape(brazil_geogcent)+tm_dots()
tm_shape(state_simple) + tm_borders() + tm_shape(state_simple_geogcent) + tm_dots()
#tm_shape(state) + tm_borders() + tm_shape(state_geogcent) + tm_dots() 
#tm_shape(munic) + tm_borders()

```



```{r}

#calculate cumulitive cases/deaths

sum_nat_cases <- allcases2 %>% group_by(epidemiological_week)%>% filter(epidemiological_week == "41") %>% summarise(sum = sum(daily.cases), sum_d = sum(daily.deaths))

sum_state_cases <- allcases2 %>% group_by(state_code, epidemiological_week)%>% filter(epidemiological_week == "41") %>% summarise(sum_cases = sum(daily.cases), sum_deaths = sum(daily.deaths))



sum_munic_cases <- allcases2 %>% group_by(ibge_code, epidemiological_week)%>% filter(epidemiological_week == "41") %>% summarise(sum_cases = sum(daily.cases), sum_deaths = sum(daily.deaths))

sum_munic_cases_investigation <- allcases2 %>% group_by(ibge_code, epidemiological_week)%>% filter(epidemiological_week == "41", state_code ==51) 
sum_munic_cases_investigation


sum_state_cases$sum_cases

#write.csv(sum_munic_cases, "/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/newdata/municweek41.csv", row.names = FALSE)

#write.csv(sum_munic_cases_investigation, "/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/newdata/state51week41.csv", row.names = FALSE)


sum_munic_cases_cumul <- allcases2 %>% group_by(ibge_code) %>% summarise(sum_cases = sum(daily.cases), sum_deaths = sum(daily.deaths))
sum_munic_cases_cumul

#write.csv(sum_munic_cases_cumul, "/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/newdata/munic_cumulative.csv", row.names = FALSE)

sum_state_cases
sum_nat_cases


cases

```


```{r}


national_weighted_centroid <- function(st, id, case_num){
  
  centroids <- st_centroid(st_geometry(st))
  
  centroid_coordinates <- do.call(rbind,centroids) %>% as_tibble() %>% setNames(c("x", "y"))
  
  st["x"] <- centroid_coordinates["x"]
  st["y"] <- centroid_coordinates["y"]
  
  st.df <- st_drop_geometry(st)
  
  nation <- unique(st.df[id]) 
  
  x <- rep(NA, length(nation))
  y <- rep(NA, length(nation))
  
  for(e in 1:nrow(nation)){
    nation_states <- st.df[which(st.df[id]==nation[e,]),]
    w <- nation_states[case_num]
    wx <- nation_states["x"]*w
    wy <- nation_states["y"]*w
    x[e] <- sum(wx)/sum(w)
    y[e] <- sum(wy)/sum(w)

  }
  output <- data.frame(nation, x, y)
  
  sf_output <- st_as_sf(output, coords=c("x", "y")) %>% st_set_crs(.,29101)
}
```





```{r}
start_week_id <- 9
end_week_id <- 41

weekly_line_merge <- st_sf(period=NA, pi=0, i=0, x_pi=0, y_pi=0, x_i = 0, y_i = 0, nm_munic=NA, geometry = st_sfc(lapply(NA, function(x) st_linestring())), cap_line = st_sfc(lapply(NA, function(x) st_linestring()))) 
weekly_line_merge <- st_set_crs(weekly_line_merge,29101)




linecols4 <- c("#73B2FF", #9
              "#6FA4FE", #10
              "#6B96FD", #11
              "#6787FD", #12
              "#6377FC",  #13
              "#5F67FB", #14
              "#5F5BFA", #15
              "#6857F9", #16
             "#7153F9", #17
             "#7B4FF8", #18
             "#864BF7", #19
              "#9148F6", #20
             "#9C44F5", #21
             "#A840F5", #22
             "#B53CF4", #23
             "#C239F3", #24
              "#CF35F2", #25
              "#DD31F1", #26
             "#EB2DF0", #27
             "#F02AE5", #28
             "#EF26D5", #29
             "#EE23C3", #30
             "#ED1FB2", #31
             "#EC1CA0", #32
             "#EC188D", #33
             "#EB147A", #34
             "#EA1167", #35
             "#E90E53", #36
             "#E80A3F", #37
             "#E8072A", #38
             "#E70315", #39
             "#E60000" #40
)

weeks <- c(9:40)
color.weeks <- data.frame(weeks, linecols4)

i = 10
for (i in start_week_id:end_week_id){
  
   a <- if(i==9){
      (i)
    } else{
      (i-1)
    }
   
  ###for current week###
  week_temp <- allcases2 %>% filter(epidemiological_week==i) %>% group_by(ibge_code, epidemiological_week) %>% summarise(sum_cases = sum(daily.cases), sum_deaths=sum(daily.deaths)) %>% select(ibge_code,epidemiological_week, sum_cases, sum_deaths) 
   
  if(i ==9 ){
    week_temp2 <-week_temp
    
    week_temp2$ibge_code <- as.character(week_temp$ibge_code)
    
        spat_temp <- left_join(munic, week_temp2, by = "ibge_code")
        spat_temp[["sum_cases"]][is.na(spat_temp[["sum_cases"]])] <- 0 
        spat_temp[["sum_deaths"]][is.na(spat_temp[["sum_deaths"]])] <- 0
          
  } else if (i == 10 ){
    spat_temp_old <- spat_temp %>% select(ibge_code, sum_cases) %>% rename(old_cases = sum_cases)
    week_temp2 <- left_join(week_temp, spat_temp_old, by = "ibge_code")
    week_temp2 <- week_temp2 %>% mutate(cumil_cases = sum_cases + old_cases)
      
      week_temp2$ibge_code <- as.character(week_temp2$ibge_code)
      
        spat_temp <- left_join(munic, week_temp2, by = "ibge_code")
        spat_temp[["sum_cases"]][is.na(spat_temp[["sum_cases"]])] <- 0 
        spat_temp[["sum_deaths"]][is.na(spat_temp[["sum_deaths"]])] <- 0
        spat_temp[["cumil_cases"]][is.na(spat_temp[["cumil_cases"]])] <- 0
        
  } else{
  spat_temp_old <- spat_temp %>% select(ibge_code, cumil_cases) %>% rename(old_cumil = cumil_cases)
    week_temp2 <- left_join(week_temp, spat_temp_old, by = "ibge_code")
    week_temp2 <- week_temp2 %>% mutate(cumil_cases = sum_cases + old_cumil)
      
      week_temp2$ibge_code <- as.character(week_temp2$ibge_code)
      
        spat_temp <- left_join(munic, week_temp2, by = "ibge_code")
        spat_temp[["sum_cases"]][is.na(spat_temp[["sum_cases"]])] <- 0 
        spat_temp[["sum_deaths"]][is.na(spat_temp[["sum_deaths"]])] <- 0
        spat_temp[["cumil_cases"]][is.na(spat_temp[["cumil_cases"]])] <- 0
    
  }
  
   
 
  centroids_temp <- national_weighted_centroid(spat_temp, "country_code", "sum_cases")
  centroids_temp["week"]<-i
  centroids_temp$week <- as.numeric(centroids_temp$week)
  centroids_temp["week_prev"] <- a
  centroids_temp["period"] <- paste0(i-1,"_",i)
  centroids_temp_geom <- centroids_temp[["geometry"]]
  
  #need to split x and y
  coords_temp <- do.call(rbind,centroids_temp_geom) %>% as_tibble() %>% setNames(c("x", "y"))
  
  centroids_temp["x"] <- coords_temp["x"]
  centroids_temp["y"] <- coords_temp["y"]
  
  centroids_temp <- st_set_crs(centroids_temp,29101)
  
  centroids_temp.df <- st_drop_geometry(centroids_temp)
  
  
  ###for previous week###

          week_temp_prev <- allcases2 %>% filter(epidemiological_week==(a)) %>% group_by(ibge_code, epidemiological_week) %>% summarise(sum_cases = sum(daily.cases), sum_deaths=sum(daily.deaths)) %>% select(ibge_code, sum_cases, sum_deaths) 
          
          spat_temp_prev <- left_join(munic, week_temp_prev, by = "ibge_code")
          spat_temp_prev[["sum_cases"]][is.na(spat_temp_prev[["sum_cases"]])] <- 0 
          spat_temp_prev$sum_deaths[is.na(spat_temp_prev$sum_deaths)] <- 0
        
          centroids_temp_prev <- national_weighted_centroid(spat_temp_prev, "country_code", "sum_cases")
             
             
              
          centroids_temp_prev["week"]<- a
          centroids_temp_prev$week <- as.numeric(centroids_temp_prev$week)
          centroids_temp_prev_geom <- centroids_temp_prev[["geometry"]]
          
          #need to split x and y
          coords_temp_prev <- do.call(rbind,centroids_temp_prev_geom) %>% as_tibble() %>% setNames(c("x", "y"))
          
          centroids_temp_prev["x"] <- coords_temp_prev["x"]
          centroids_temp_prev["y"] <- coords_temp_prev["y"]

          centroids_temp_prev.df <- st_drop_geometry(centroids_temp_prev)
          
          
    cent_munic_join <- st_join(centroids_temp, munic["NM_MUNICIP"])
    cent_munic_join.df <- st_drop_geometry(cent_munic_join)
    
    capital_temp <- capital
    capital_temp_geom <- capital[["geometry"]]
    capital_coords_temp <- do.call(rbind,capital_temp_geom) %>% as_tibble() %>% setNames(c("x", "y"))
    capital_temp <- st_drop_geometry(capital_temp)
          
          capital_temp["x"] <- capital_coords_temp["x"]
          capital_temp["y"] <- capital_coords_temp["y"]
          
    ### getting weekly change in coordinates as lines
    weekly_cent_temp  <- st_as_sf(data.frame(period = paste0(a,"_",i),
                                    pi = centroids_temp.df["week_prev"],
                                    i = centroids_temp.df["week"],
                                    x_pi = centroids_temp_prev.df["x"],
                                    y_pi = centroids_temp_prev.df["y"],
                                    x_i = centroids_temp.df["x"],
                                    y_i = centroids_temp.df["y"],
                                    x_cap = capital_temp["x"],
                                    y_cap = capital_temp["y"],
                                    nm_munic = cent_munic_join.df["NM_MUNICIP"],
                                    geometry= centroids_temp_geom))
    names(weekly_cent_temp) <- c('period', 'pi', 'i', 'x_pi', 'y_pi','x_i','y_i','x_cap', 'y_cap','nm_munic', 'geometry')
    
    weekly_cent_temp$geometry <- st_sfc(st_linestring(rbind(st_point(c(weekly_cent_temp$x_pi, weekly_cent_temp$y_pi)), st_point(c(weekly_cent_temp$x_i, weekly_cent_temp$y_i)))))
    weekly_cent_temp$cap_line <- st_sfc(st_linestring(rbind(st_point(c(weekly_cent_temp$x_i, weekly_cent_temp$y_i)), st_point(c(weekly_cent_temp$x_cap, weekly_cent_temp$y_cap)))))
    weekly_cent_temp <- st_set_crs(weekly_cent_temp,29101)
    weekly_cent_temp <-weekly_cent_temp %>% select(!"x_cap") %>% select(!"y_cap") %>% st_set_crs(.,29101) %>% st_transform(.,29101)
  
  
  weekly_line_merge <- rbind(weekly_line_merge,weekly_cent_temp) %>% filter(!is.na(period)) %>% filter(period!="9_9") 
  weekly_line_merge<- weekly_line_merge %>% st_set_crs(.,29101) %>% st_transform(.,29101) 
  
  #weekly_line_merge<- weekly_line_merge %>% rename("period" = "period")
    
  
  maxval_temp <- max(spat_temp$cumil_cases)
  
  if(maxval_temp < 10001){
    maxval_temp2.nm <- 10000.1
    maxval_temp2.chr <- "1,001 - 10,000"
    maxval_temp3.nm <- 100000
    maxval_temp3.chr <- "10,001 - 100,000"
    maxval_temp4.nm <- 1000000.1
    maxval_temp4.chr <- "> 100,000"
    
  } else if(maxval_temp >= 10001 & maxval_temp < 100001){
    maxval_temp2.nm <- 10000.1
    maxval_temp2.chr <- "1,001 - 10,000"
    maxval_temp3.nm <- 100000.1
    maxval_temp3.chr <- "10,001 - 100,000"
    maxval_temp4.nm <- 1000000.1
    maxval_temp4.chr <- "> 100,000"
    
  } else{
    maxval_temp2.nm <- 10000.1
    maxval_temp2.chr <- "1,001 - 10,000"
    maxval_temp3.nm <- 100000.1
    maxval_temp3.chr <- "10,001 - 100,000"
    maxval_temp4.nm <- maxval_temp
    maxval_temp4.chr <- maxval_temp %>% formatC(., format="f", big.mark=",", digits=0)
    maxval_temp4.chr <- paste0("100,001 - ", maxval_temp4.chr)
  }
  
  if(i == 9){
  
  nbin9 <- tm_shape(brazil) + tm_borders(lwd=0.5) + tm_shape(spat_temp) + tm_fill(col="sum_cases", palette = "OrRd", breaks=c(0, 100.1,1000.1,maxval_temp2.nm,maxval_temp3.nm, maxval_temp4.nm), title = "Total Cases", alpha=0.5, labels = c("< 101","101 - 1,000", maxval_temp2.chr, maxval_temp3.chr, maxval_temp4.chr)) + tm_shape(state_simple) + tm_borders(col="gray60", lwd=0.5) + tm_layout(main.title = "COVID-19 Case-Weighted Centroid for Brazil", main.title.size = 1.5, main.title.position = "center", frame=FALSE, legend.outside = TRUE) + tm_credits(paste0("Week ", i), size=1,position= "left") + tm_shape(centroids_temp) + tm_bubbles(size=0.5, border.col="red", border.lwd=1.2, border.alpha=1, col="white", alpha=0.1) + tm_scale_bar(breaks = c(0,500,1000), color.dark = "gray60", position = c("right", "bottom"),just="right", width = 0.15, text.color = "gray60")
 print(nbin9)

  tmap_save(nbin9, paste0("//Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/animations_cumil/natmap_week",i,".png"))
  
  } else {

    color <- color.weeks$linecols4
    
    weekly_line_merge <- weekly_line_merge %>% select(period, pi, i, x_pi, y_pi, x_i, y_i, nm_munic, geometry, cap_line) %>% rename(Period = i)
    weekly_line_merge$Period <- as.character(weekly_line_merge$Period)
    
   nbin <- tm_shape(brazil) + tm_borders(lwd=0.5) + tm_shape(spat_temp) + tm_fill(col="cumil_cases", palette = "OrRd", breaks=c(0, 100.1,1000.1,maxval_temp2.nm,maxval_temp3.nm, maxval_temp4.nm), title = "Total Cases", alpha=0.5, labels = c("=< 100","101 - 1,000", maxval_temp2.chr, maxval_temp3.chr, maxval_temp4.chr)) + tm_shape(state_simple) + tm_borders(col="gray60", lwd=0.5) + tm_layout(main.title = "COVID-19 Case-Weighted Centroid for Brazil", main.title.size = 1.5, main.title.position = "center", frame=FALSE, legend.outside = TRUE) + tm_credits(paste0("Week ", i), size=1,position= "left") + tm_shape(weekly_line_merge) + tm_lines(col="Period", lwd=3, palette = color, labels = c ("9 - 10", "10 - 11", "11 - 12", "12 - 13", "13 - 14", "14 - 15", "15 - 16", "16 - 17", "17 - 18", "18 - 19", "19 - 20", "20 - 21", "21 - 22", "22 - 23", "23 - 24", "24 - 25", "25 - 26", "26 - 27", "27 - 28", "28 - 29", "29 - 30", "30 - 31", "31 - 32", "32 - 33", "33 - 34", "34 - 35", "35 - 36","36 - 37", "37 - 38", "38 - 39", "39 - 40", "40 - 41")) + tm_shape(centroids_temp) + tm_bubbles(size=0.5, border.col="red", border.lwd=1.2, border.alpha=1, col="white", alpha=0.1) + tm_scale_bar(breaks = c(0,500,1000), color.dark = "gray60", position = c("right", "bottom"),just="right", text.color = "gray60")
  print(nbin) 
  
 tmap_save(nbin, paste0("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/animations_cumil/natmap_labels",i,".png"))
  
 weekly_line_merge$Period <- as.numeric(weekly_line_merge$Period)
 
  weekly_line_merge<- weekly_line_merge %>% select(period, pi, Period, x_pi, y_pi, x_i, y_i, nm_munic, geometry, cap_line) %>% rename(i= Period)
  
    
  }
  
    

}




```


```{r}
library(magick)
list.files(path='/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/animations_cumil/', pattern = '*.png', full.names = TRUE) %>% 
        image_read() %>% # reads each path file
        image_join() %>% # joins image
        image_animate(delay=100) %>% # animates, can opt for number of loops
        image_write("/Users/erin/Desktop/Harvard_NSF_REU/Brazil_COVID/animations_cumil/Nation_deaths_centroids.gif") # write to current dir

```








